---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: pttg-euro-tlr-enquiry-form
  namespace: {{.KUBE_NAMESPACE}}
spec:
  podSelector: {}
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            name: ingress-external
  egress:
    - {}