---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pttg-euro-tlr-maintenance
  labels:
    version: {{.VERSION}}
spec:
  replicas: 4
  selector:
    matchLabels:
      name: pttg-euro-tlr-maintenance
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: pttg-euro-tlr-maintenance
        version: {{.VERSION}}
    spec:
      containers:
      - name: certs
        image: quay.io/ukhomeofficedigital/cfssl-sidekick:v0.0.6
        securityContext:
          runAsNonRoot: true
          capabilities:
            drop:
             - SETUID
             - SETGID
        args:
          - --certs=/certs
          - --domain=pttg-euro-tlr-maintenance.${KUBE_NAMESPACE}.svc.cluster.local
          - --expiry=8760h
          - --command=chmod +r /certs/* && /usr/local/scripts/trigger_nginx_reload.sh
        env:
          - name: KUBE_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        volumeMounts:
          - name: certs
            mountPath: /certs
          - name: bundle
            mountPath: /etc/ssl/certs
            readOnly: true
      - name:  pttg-euro-tlr-maintenance
        image: quay.io/ukhomeofficedigital/pttg-enquiry-form-maintenance:EE-27635-initial-setup
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsNonRoot: true
          capabilities:
            drop:
             - SETUID
             - SETGID
        resources:
          limits:
            memory: "100Mi"
            cpu: 100m
          requests:
            memory: "50Mi"
            cpu: 100m
        env:
          - name: SERVER_CERT
            value: /certs/tls.pem
          - name: SERVER_KEY
            value: /certs/tls-key.pem
        volumeMounts:
          - name: certs
            mountPath: /certs
            readOnly: true
        ports:
          - name: https
            containerPort: 10443
      volumes:
        - name: certs
          emptyDir:
            medium: "Memory"
        - name: bundle
          configMap:
            name: bundle
