---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: pttg-euro-tlr-maintenance
  name: pttg-euro-tlr-maintenance
spec:
  ports:
  - name: https
    port: 443
    targetPort: 10443
  selector:
    name: pttg-euro-tlr-maintenance
